/// ═══════════════════════════════════════════════════════════════
/// AUTO-GENERATED by BotForge — DO NOT EDIT MANUALLY
/// Organisation: My Business (6415b4b7-a367-4803-95c3-572377e9a19c)
/// Generated: 2026-04-23T18:48:35.603Z
/// Chatbot ID: 058c3b70-ce68-40ee-a4cf-38d64348290a
/// API Key: 
/// ═══════════════════════════════════════════════════════════════
library;

class AppConfig {
  AppConfig._();

  // ── Brand Identity ──────────────────────────────────────────────
  static const String businessName   = 'My Business';
  static const String tagline        = '';
  static const String botName        = 'Assistant';
  static const String botRole        = 'Customer Experience Assistant';
  static const String welcomeMessage = 'string';

  static const List<String> quickReplies = [
    'Pricing',
    'Services',
    'Contact'
  ];

  // ── Visuals ──────────────────────────────────────────────────────
  static const String primaryColorHex = '#6C63FF';
  static const String accentColorHex  = '#FF6584';
  static const String botAvatarAsset  = 'assets/images/bot_avatar.png';
  static const String logoAsset       = 'assets/images/logo.png';

  // ── Backend ──────────────────────────────────────────────────────
  static const String apiBaseUrl     = 'https://api.example.com';
  static const String chatEndpoint   = '/chatbots/mobile/:chatbotId';
  static const String organisationId = '6415b4b7-a367-4803-95c3-572377e9a19c';
  static const String chatbotId = '058c3b70-ce68-40ee-a4cf-38d64348290a';
  static const String apiKey = '';

  // ── Chat Session ────────────────────────────────────────────────
  static const String chatId = '';  // Generated on first chat

  // ── Business Hours ───────────────────────────────────────────────
  static const bool   showBusinessHours = false;
  static const String businessHours     = '';
  static const String offlineMessage    =
      'We are currently outside business hours. I will still do my best to help, '
      'but a human agent will follow up. 🌙';

  // ── Social / Contact ─────────────────────────────────────────────
  static const String whatsappNumber  = '';
  static const String telegramHandle  = '';
  static const String supportEmail    = '';
  static const String websiteUrl      = '';

  // ── Feature Flags ─────────────────────────────────────────────────
  static const bool enableFileAttachments = true;
  static const bool enableVoiceMessages   = false;
  static const bool enableRatings         = true;
  static const bool enableTypingIndicator = true;
  static const bool enableReadReceipts    = true;
}